### PR TITLE
Add Reagent Project

### PR DESCRIPTION
**Pull request by mopemope**
Add Reagent project (with figwheel)

### CODE REVIEW

**Comment by mopemope** [comment]
@karad Thanks. Fixed.

**Comment by karad** [comment]
I try to run your reagent project. but I saw message "Reagent does not work." on Electron window.
I think you have to fix template in resources for +reagent mode.

in resources/leiningen/new/descjop/reagent__project.clj

```
               :frontend {:id "{{name}}-reagent"
                          :source-paths ["src_front"]
                          :incremental true
                          :jar true
                          :assert true
                          :compiler {:output-to "app/js/front.js"
                                     :externs ["app/js/externs.js"]
                                     :warnings true
                                     :elide-asserts true

                                     ;; no optimize compile (dev)
                                     :optimizations :none            // <- uncomment
                                     ;; when no optimize uncomment
                                     :output-dir "app/js/out"        // <- uncomment

                                     ;; simple compile (dev)
                                     ;;:optimizations :simple

                                     ;; advanced compile (prod)
                                     ;;:optimizations :advanced      // <- comment and change advanced

                                     ;;:source-map "app/js/test.js.map"
                                     :pretty-print true
                                     :output-wrapper true
                                     }}}}
```

**Comment by mopemope** [comment]
reagent project need 2 tasks .
try it.

```
$ lein trampoline cljsbuild auto main
```

and run another terminal

```
$ lein trampoline figwheel frontend
```

`figwheel` support only `frontend`

**Comment by karad** [comment]
Oh thanks!
I'll try it.

**Pull request merged**
