### PR TITLE
update electron version -> 1.2.5

### PR DESCRIPTION
**Pull request by toku345**
I want to use the newest Electron.
So update electron version -> 1.2.5!

I'm a electron & cljs beginner... 
I'm very grad to correct a mistake if i make it 😄 

---

image

### CODE REVIEW

**Comment by toku345** [comment]
On my

**Comment by toku345** [comment]
Sorry... 
I accidentally click the close button.
(and reopen this PR)

**Comment by karad** [comment]
Thank you for your pull request!! I will check it!!!

**Comment by toku345** [comment]
@karad Thank you for your acceptance!!!

**Pull request merged**
